version: "3.4"

services:
  router:
    build: src/router
    privileged: true
    mac_address: 02:42:ac:10:ef:0c
    networks:
      demo_net:
        ipv4_address: 172.16.239.12
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.disable_ipv6=1
    environment:
      - DRIVER=afxdp
      - ROUTER=172.16.239.12
      - ROUTER_MAC=02:42:ac:10:ef:0c
      - CLIENT=172.16.239.13
      - CLIENT_MAC=02:42:ac:10:ef:0b
      - SERVER=172.16.239.14
      - SERVER_MAC=02:42:ac:10:ef:0a

  client:
    build: src/pod
    privileged: true
    mac_address: 02:42:ac:10:ef:0b
    entrypoint: /opt/example/client.sh
    networks:
      demo_net:
        ipv4_address: 172.16.239.13
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    environment:
      - ROUTER=172.16.239.12
      - ROUTER_MAC=02:42:ac:10:ef:0c
      - CLIENT=172.16.239.13
      - CLIENT_MAC=02:42:ac:10:ef:0b
      - SERVER=172.16.239.14
      - SERVER_MAC=02:42:ac:10:ef:0a

  service:
    build: src/pod
    privileged: true
    mac_address: 02:42:ac:10:ef:0a
    entrypoint: /opt/example/service.sh
    networks:
      demo_net:
        ipv4_address: 172.16.239.14
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    environment:
      - ROUTER=172.16.239.12
      - ROUTER_MAC=02:42:ac:10:ef:0c
      - CLIENT=172.16.239.13
      - CLIENT_MAC=02:42:ac:10:ef:0b
      - SERVER=172.16.239.14
      - SERVER_MAC=02:42:ac:10:ef:0a

networks:
  demo_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.239.0/24"
